language: node_js
node_js:
  - 10.15.0
cache:
  directories:
    - node_modules
    - functions/node_modules
before_install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
script:
after_success:
  - npm run build
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master